stages:
  - build
  - scan

variables:
  REGISTRY_URI: 865494649634.dkr.ecr.us-east-1.amazonaws.com
  REPO_NAME: krypticthadonbeats-dev
  DOCKER_TAG: $CI_COMMIT_SHA
  DOCKER_IMAGE: $REGISTRY_URI/$REPO_NAME:$DOCKER_TAG

build:
  stage: build
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  services:
    - docker:dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  before_script:
  - apk add --no-cache docker
  - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
  - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
  - aws configure set region "$AWS_REGION"
  script:
      # Login to ECR
    - aws ecr get-login-password | docker login --username AWS --password-stdin $REGISTRY_URI
    - echo "Navigating to the application front directory"
    - cd application/frontend
    - ls
    - echo "Building and tagging the image with REPO_NAME = $REPO_NAME & image_tag = $DOCKER_TAG"
    - docker build -t $REPO_NAME:$DOCKER_TAG .
    - docker tag $REPO_NAME:$DOCKER_TAG $DOCKER_IMAGE
    - echo "Pushing to $REGISTRY_URI registry"
    - docker push $DOCKER_IMAGE
  after_script:
    - docker logout $REGISTRY_URI

container_scanning:
  stage: scan
  image: docker:latest
  services:
    - docker:dind
  needs: ["build"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  before_script:
    - apk add --no-cache curl
  script:
    - echo "$AWS_ACCESS_KEY_ID" | docker login -u "$AWS_ACCESS_KEY_ID" --password-stdin $REGISTRY_URI
    # Install Docker Scout
    - curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
    - sh install-scout.sh
    # Authenticate Docker Scout
    - echo "$DOCKER_SCOUT_TOKEN" | docker login -u "$DOCKER_SCOUT_HUB_USERNAME" --password-stdin
    # Run CVES scan
    - docker scout cves $DOCKER_IMAGE > cves-report.txt
    # Quickview with potential failure on critical issues
    - docker scout quickview $DOCKER_IMAGE
  artifacts:
    paths:
      - cves-report.txt
    when: always
  after_script:
    - docker logout $REGISTRY_URI