name: Trivy Container scanning

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      azure_registry:
        required: true
      azure_registry_name:
        required: true

jobs:
  trivy_scan:
    name: Trivy Container Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag environment variables
        run: |
          echo "DOCKER_IMAGE=${{ secrets.azure_registry }}/${{ secrets.azure_registry_name }}:${{ inputs.image_tag }}" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: application
        run: |
          docker build -t $DOCKER_IMAGE .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
